<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="testbtb.aspx.cs" Inherits="Handing.Reports.WholeDesign.testbtb" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>jQuery.ajax异步提交方式</title>
    <style type="text/css">
        td {
            padding: 5px;
        }

        tr td:first-child {
            text-align: right;
        }

        caption {
            font-weight: bolder;
            color: red;
        }

        form {
            margin: 20px;
        }
    </style>

   <script src="/Scripts/jquery-1.7.1.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $("#btnAjaxSubmit").click(function () {
                var options = {
                    //url: 'testbb.aspx?action=SaveUserInfo',
                    url: '/Reports/WholeDesign/testbtb.aspx?action=SaveUserInfo',
                    type: 'post',
                    dataType: 'text',
                    data: $("#form1").serialize(),
                    success: function (data) {
                        //var json = eval("(" + data + ")");
                        //alert(data)
                        if (data.length > 0)
                            $("#responseText").html(data + "\n");

                    }
                };
                $.ajax(options);
                return false;
            });
        });
    </script>
</head>
<body>
    <form id="form1" method="post" runat="server">
        <table border="1">
            <caption>jQuery.ajax异步提交方式</caption>
            <tr>
                <td>用户名：</td>
                <td>
                    <input type="text" name="loginName" /></td>
            </tr>
            <tr>
                <td>性  别：</td>
                <td>
                    <input type="radio" name="sex" value="0" checked="checked" />男
                    &nbsp;&nbsp;
                    <input type="radio" name="sex" value="1" />女
                </td>
            </tr>
            <tr>
                <td>爱  好：</td>
                <td>
                    <input type="checkbox" name="cbLoveYy" value="1" />游泳
                    <input type="checkbox" name="cbLoveYx" value="1" />游戏
                    <input type="checkbox" name="cbLovePs" value="1" />爬山
                </td>
            </tr>
            <tr>
                <td>所属国家：</td>
                <td>
                    <select name="country">
                        <option value="请选择" selected="selected">请选择</option>
                        <option value="M7">M7</option>
                        <option value="M6">M6</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center">
                    <input id="btnAjaxSubmit" type="submit" value="jQuery提交" />
                </td>
            </tr>
        </table>
         <asp:GridView ID="MyGridView" runat="server" 
             CssClass="mg-gridview"
             AllowPaging="true" 
             AllowSorting="true" 
             AutoGenerateColumns="false" 
             AutoGenerateDeleteButton="False"
             >
         <SelectedRowStyle CssClass="mg-selectrowstyle" />
         <HeaderStyle CssClass="GridViewHeaderStyle"/>
         <RowStyle CssClass="GridViewRowStyle"/> 
            <Columns>
            <asp:BoundField DataField="HD_Id" HeaderText="编号" ShowHeader="false" SortExpression="HD_Id" />
            <asp:BoundField DataField="Capacity" HeaderText="起重量" SortExpression="Capacity" />
                <asp:BoundField DataField="FEM" HeaderText="FEM" SortExpression="FEM" />
                <asp:BoundField DataField="v" HeaderText="起升速度" SortExpression="v" />
                <asp:BoundField DataField="p" HeaderText="电机功率" SortExpression="p" />
               
            </Columns>
         
        </asp:GridView>
    </form>
    <br />
    <div id="responseText"></div>


</body>
</html>

          